export interface Env { DB:D1Database; DISCORD_CLIENT_ID:string; DISCORD_CLIENT_SECRET:string; DISCORD_REDIRECT_URI:string; OWNER_DISCORD_USER_ID:string; ANDROID_APP_URL:string; }
const headers={"content-type":"application/json; charset=utf-8","access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,PUT,DELETE,OPTIONS","access-control-allow-headers":"Content-Type, Authorization"};
const out=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});
async function userFromToken(req:Request,env:Env){const a=req.headers.get("Authorization")||"";if(!a.startsWith("Bearer "))return null;return await env.DB.prepare("SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND datetime(s.expires_at)>datetime('now') LIMIT 1").bind(a.slice(7)).first();}
async function requireUser(req:Request,env:Env){const u:any=await userFromToken(req,env);if(!u)throw new Error("UNAUTHORIZED");if(Number(u.disabled))throw new Error("ACCOUNT_DISABLED");return u;}
const isAdmin=(u:any)=>["OWNER","SUPER_ADMIN","ADMIN","MODERATOR","STORE_MANAGER"].includes(String(u.role));
async function audit(env:Env,u:any,action:string,targetType?:string,targetId?:number,details?:string){await env.DB.prepare("INSERT INTO audit_log(actor_id,action,target_type,target_id,details) VALUES(?,?,?,?,?)").bind(u.id,action,targetType||null,targetId||null,details||null).run();}
async function notify(env:Env,userId:number,type:string,title:string,body:string){await env.DB.prepare("INSERT INTO notifications(user_id,type,title,body) VALUES(?,?,?,?)").bind(userId,type,title,body).run();}
async function discordToken(env:Env,code:string){const body=new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,client_secret:env.DISCORD_CLIENT_SECRET,grant_type:"authorization_code",code,redirect_uri:env.DISCORD_REDIRECT_URI});const r=await fetch("https://discord.com/api/oauth2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body});if(!r.ok)throw new Error("DISCORD_TOKEN_FAILED");return await r.json() as any;}
async function discordUser(accessToken:string){const r=await fetch("https://discord.com/api/users/@me",{headers:{Authorization:`Bearer ${accessToken}`}});if(!r.ok)throw new Error("DISCORD_USER_FAILED");return await r.json() as any;}
function avatarUrl(u:any){return u.avatar?`https://cdn.discordapp.com/avatars/${u.id}/${u.avatar}.png?size=256`:null;}
function esc(s:any){return String(s??"").trim();}
async function postList(env:Env,u:any,mode:string){let q=`SELECT p.*,u.username,u.display_name,u.avatar_url,u.server_code,(SELECT COUNT(*) FROM likes l WHERE l.post_id=p.id) likes_count,(SELECT COUNT(*) FROM comments c WHERE c.post_id=p.id) comments_count,(SELECT COUNT(*) FROM bookmarks b WHERE b.post_id=p.id AND b.user_id=?) bookmarked FROM posts p JOIN users u ON u.id=p.user_id WHERE u.disabled=0 AND p.hidden=0 AND NOT EXISTS(SELECT 1 FROM blocks b WHERE b.blocker_id=? AND b.blocked_id=u.id)`;const args:any[]=[u?.id||0,u?.id||0];if(mode==="following"){q+=` AND (p.user_id=? OR EXISTS(SELECT 1 FROM follows f WHERE f.follower_id=? AND f.following_id=p.user_id))`;args.push(u.id,u.id);}q+=" ORDER BY p.pinned DESC,p.id DESC LIMIT 100";return (await env.DB.prepare(q).bind(...args).all()).results;}
export default {async fetch(request:Request,env:Env){if(request.method==="OPTIONS")return new Response(null,{headers});const url=new URL(request.url),path=url.pathname,method=request.method;try{
if(path==="/"&&method==="GET")return out({name:"OneState Hub API",status:"online",version:"3.0.0"});
if(path==="/health"&&method==="GET"){await env.DB.prepare("SELECT 1").first();return out({ok:true,database:true});}
if(path==="/auth/discord"&&method==="GET"){const p=new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,response_type:"code",redirect_uri:env.DISCORD_REDIRECT_URI,scope:"identify"});return Response.redirect(`https://discord.com/oauth2/authorize?${p}`,302);}
if(path==="/auth/discord/callback"&&method==="GET"){const code=url.searchParams.get("code");if(!code)return out({error:"missing_code"},400);const token=await discordToken(env,code),du=await discordUser(token.access_token),role=du.id===env.OWNER_DISCORD_USER_ID?"OWNER":"USER";await env.DB.prepare(`INSERT INTO users(discord_id,username,avatar_url,display_name,role) VALUES(?,?,?,?,?) ON CONFLICT(discord_id) DO UPDATE SET username=excluded.username,avatar_url=excluded.avatar_url,role=?,updated_at=CURRENT_TIMESTAMP`).bind(du.id,du.username,avatarUrl(du),du.global_name||du.username,role,role).run();const user:any=await env.DB.prepare("SELECT id FROM users WHERE discord_id=?").bind(du.id).first();const session=crypto.randomUUID();await env.DB.prepare("INSERT INTO sessions(token,user_id,expires_at,created_at) VALUES(?,?,datetime('now','+30 days'),datetime('now'))").bind(session,user.id).run();await notify(env,user.id,"SYSTEM","مرحبًا بك في OneState Hub","تم تسجيل دخولك بنجاح.");const target=new URL(env.ANDROID_APP_URL||"onestatehub://auth/callback");target.searchParams.set("token",session);target.searchParams.set("role",role);return new Response(null,{status:302,headers:{Location:target.toString()}});}
if(path==="/me"&&method==="GET")return out(await requireUser(request,env));
if(path==="/auth/logout"&&method==="POST"){const a=request.headers.get("Authorization")||"";if(a.startsWith("Bearer "))await env.DB.prepare("DELETE FROM sessions WHERE token=?").bind(a.slice(7)).run();return out({ok:true});}
if(path==="/me/setup"&&method==="POST"){const u:any=await requireUser(request,env),b:any=await request.json();await env.DB.prepare("UPDATE users SET region=?,server_code=?,display_name=COALESCE(NULLIF(?,''),display_name),bio=COALESCE(?,bio),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(esc(b.region),esc(b.server_code),esc(b.display_name),b.bio??null,u.id).run();return out({ok:true});}
if(path==="/me"&&method==="PUT"){const u:any=await requireUser(request,env),b:any=await request.json();await env.DB.prepare("UPDATE users SET display_name=COALESCE(?,display_name),bio=COALESCE(?,bio),avatar_url=COALESCE(?,avatar_url),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.display_name??null,b.bio??null,b.avatar_url??null,u.id).run();return out({ok:true});}
if(path==="/posts"&&method==="GET"){const u:any=await requireUser(request,env).catch(()=>null);return out(await postList(env,u,url.searchParams.get("feed")==="following"?"following":"all"));}
if(path==="/posts"&&method==="POST"){const u:any=await requireUser(request,env),b:any=await request.json(),body=esc(b.body);if(!body)return out({error:"post_body_required"},400);const r=await env.DB.prepare("INSERT INTO posts(user_id,body,media_url,media_type) VALUES(?,?,?,?)").bind(u.id,body,b.media_url||null,b.media_type||null).run();return out({ok:true,id:r.meta.last_row_id},201);}
if(/^\/posts\/\d+$/.test(path)&&method==="PUT"){const u:any=await requireUser(request,env),id=Number(path.split("/")[2]),b:any=await request.json(),p:any=await env.DB.prepare("SELECT * FROM posts WHERE id=?").bind(id).first();if(!p)return out({error:"not_found"},404);if(p.user_id!==u.id&&!isAdmin(u))return out({error:"forbidden"},403);await env.DB.prepare("UPDATE posts SET body=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(esc(b.body),id).run();await audit(env,u,"EDIT_POST","POST",id);return out({ok:true});}
if(/^\/posts\/\d+$/.test(path)&&method==="DELETE"){const u:any=await requireUser(request,env),id=Number(path.split("/")[2]),p:any=await env.DB.prepare("SELECT * FROM posts WHERE id=?").bind(id).first();if(!p)return out({error:"not_found"},404);if(p.user_id!==u.id&&!isAdmin(u))return out({error:"forbidden"},403);await env.DB.prepare("DELETE FROM posts WHERE id=?").bind(id).run();await audit(env,u,"DELETE_POST","POST",id);return out({ok:true});}
if(/^\/posts\/\d+\/(like|bookmark)$/.test(path)&&method==="POST"){const u:any=await requireUser(request,env),parts=path.split("/"),id=Number(parts[2]),kind=parts[3],table=kind==="like"?"likes":"bookmarks";const exists=await env.DB.prepare(`SELECT 1 FROM ${table} WHERE post_id=? AND user_id=?`).bind(id,u.id).first();if(exists){await env.DB.prepare(`DELETE FROM ${table} WHERE post_id=? AND user_id=?`).bind(id,u.id).run();return out({active:false});}await env.DB.prepare(`INSERT INTO ${table}(post_id,user_id) VALUES(?,?)`).bind(id,u.id).run();const p:any=await env.DB.prepare("SELECT user_id FROM posts WHERE id=?").bind(id).first();if(p&&p.user_id!==u.id)await notify(env,p.user_id,kind.toUpperCase(),kind==="like"?"إعجاب جديد":"حفظ منشور","لديك تفاعل جديد على منشورك.");return out({active:true});}
if(/^\/posts\/\d+\/comments$/.test(path)&&method==="GET"){const id=Number(path.split("/")[2]);return out((await env.DB.prepare("SELECT c.*,u.username,u.display_name FROM comments c JOIN users u ON u.id=c.user_id WHERE c.post_id=? ORDER BY c.id ASC").bind(id).all()).results);}
if(/^\/posts\/\d+\/comments$/.test(path)&&method==="POST"){const u:any=await requireUser(request,env),id=Number(path.split("/")[2]),b:any=await request.json();const r=await env.DB.prepare("INSERT INTO comments(post_id,user_id,body) VALUES(?,?,?)").bind(id,u.id,esc(b.body)).run();const p:any=await env.DB.prepare("SELECT user_id FROM posts WHERE id=?").bind(id).first();if(p&&p.user_id!==u.id)await notify(env,p.user_id,"COMMENT","تعليق جديد","تم التعليق على منشورك.");return out({ok:true,id:r.meta.last_row_id},201);}
if(/^\/comments\/\d+$/.test(path)&&method==="PUT"){const u:any=await requireUser(request,env),id=Number(path.split("/")[2]),b:any=await request.json(),c:any=await env.DB.prepare("SELECT * FROM comments WHERE id=?").bind(id).first();if(!c||c.user_id!==u.id&&!isAdmin(u))return out({error:"forbidden"},403);await env.DB.prepare("UPDATE comments SET body=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(esc(b.body),id).run();return out({ok:true});}
if(/^\/comments\/\d+$/.test(path)&&method==="DELETE"){const u:any=await requireUser(request,env),id=Number(path.split("/")[2]),c:any=await env.DB.prepare("SELECT * FROM comments WHERE id=?").bind(id).first();if(!c||c.user_id!==u.id&&!isAdmin(u))return out({error:"forbidden"},403);await env.DB.prepare("DELETE FROM comments WHERE id=?").bind(id).run();return out({ok:true});}
if(path==="/follow"&&method==="POST"){const u:any=await requireUser(request,env),b:any=await request.json(),target:any=await env.DB.prepare("SELECT * FROM users WHERE id=? OR discord_id=? LIMIT 1").bind(b.user_id??-1,b.discord_id??"").first();if(!target||target.id===u.id)return out({error:"invalid_target"},400);const ex=await env.DB.prepare("SELECT 1 FROM follows WHERE follower_id=? AND following_id=?").bind(u.id,target.id).first();if(ex){await env.DB.prepare("DELETE FROM follows WHERE follower_id=? AND following_id=?").bind(u.id,target.id).run();return out({following:false});}await env.DB.prepare("INSERT INTO follows(follower_id,following_id) VALUES(?,?)").bind(u.id,target.id).run();await notify(env,target.id,"FOLLOW","متابعة جديدة",`${u.display_name||u.username} بدأ بمتابعتك.`);return out({following:true});}
if(path==="/block"&&method==="POST"){const u:any=await requireUser(request,env),b:any=await request.json(),id=Number(b.user_id);if(!id||id===u.id)return out({error:"invalid_target"},400);const ex=await env.DB.prepare("SELECT 1 FROM blocks WHERE blocker_id=? AND blocked_id=?").bind(u.id,id).first();if(ex)await env.DB.prepare("DELETE FROM blocks WHERE blocker_id=? AND blocked_id=?").bind(u.id,id).run();else await env.DB.prepare("INSERT INTO blocks(blocker_id,blocked_id) VALUES(?,?)").bind(u.id,id).run();return out({blocked:!ex});}
if(path==="/notifications"&&method==="GET"){const u:any=await requireUser(request,env);return out((await env.DB.prepare("SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 100").bind(u.id).all()).results);}
if(/^\/notifications\/\d+\/read$/.test(path)&&method==="POST"){const u:any=await requireUser(request,env),id=Number(path.split("/")[2]);await env.DB.prepare("UPDATE notifications SET read=1 WHERE id=? AND user_id=?").bind(id,u.id).run();return out({ok:true});}
if(path==="/messages"&&method==="GET"){const u:any=await requireUser(request,env),other=Number(url.searchParams.get("user_id"));if(!other)return out({error:"user_id_required"},400);return out((await env.DB.prepare("SELECT m.*,s.display_name sender_name,r.display_name receiver_name FROM messages m JOIN users s ON s.id=m.sender_id JOIN users r ON r.id=m.receiver_id WHERE (sender_id=? AND receiver_id=?) OR (sender_id=? AND receiver_id=?) ORDER BY m.id ASC LIMIT 200").bind(u.id,other,other,u.id).all()).results);}
if(path==="/messages"&&method==="POST"){const u:any=await requireUser(request,env),b:any=await request.json(),to=Number(b.receiver_id),body=esc(b.body);if(!to||!body)return out({error:"receiver_and_body_required"},400);const r=await env.DB.prepare("INSERT INTO messages(sender_id,receiver_id,body,media_url,media_type) VALUES(?,?,?,?,?)").bind(u.id,to,body,b.media_url||null,b.media_type||null).run();await notify(env,to,"MESSAGE","رسالة جديدة",`لديك رسالة جديدة من ${u.display_name||u.username}.`);return out({ok:true,id:r.meta.last_row_id},201);}
if(path==="/reports"&&method==="POST"){const u:any=await requireUser(request,env),b:any=await request.json();const r=await env.DB.prepare("INSERT INTO reports(reporter_id,target_type,target_id,reason) VALUES(?,?,?,?)").bind(u.id,esc(b.target_type),Number(b.target_id),esc(b.reason)).run();return out({ok:true,id:r.meta.last_row_id},201);}
if(path==="/search"&&method==="GET"){const u:any=await requireUser(request,env),q=`%${esc(url.searchParams.get("q"))}%`;const users=(await env.DB.prepare("SELECT id,username,display_name,avatar_url,server_code,role FROM users WHERE disabled=0 AND (username LIKE ? OR display_name LIKE ?) LIMIT 30").bind(q,q).all()).results;const posts=(await env.DB.prepare("SELECT p.id,p.body,u.display_name,u.server_code FROM posts p JOIN users u ON u.id=p.user_id WHERE p.hidden=0 AND p.body LIKE ? ORDER BY p.id DESC LIMIT 30").bind(q).all()).results;const listings=(await env.DB.prepare("SELECT id,title,category,price,server_code FROM listings WHERE status='ACTIVE' AND (title LIKE ? OR description LIKE ?) LIMIT 30").bind(q,q).all()).results;return out({users,posts,listings});}
if(path==="/market"&&method==="GET"){const server=url.searchParams.get("server");if(!server)return out({error:"server_required"},400);return out((await env.DB.prepare("SELECT l.*,u.username,u.display_name,u.avatar_url FROM listings l JOIN users u ON u.id=l.user_id WHERE l.server_code=? AND l.status='ACTIVE' AND u.disabled=0 ORDER BY l.id DESC LIMIT 100").bind(server).all()).results);}
if(path==="/market"&&method==="POST"){const u:any=await requireUser(request,env),b:any=await request.json();if(!b.server_code||!b.category||!b.title||b.price===undefined)return out({error:"server_category_title_price_required"},400);const r=await env.DB.prepare("INSERT INTO listings(user_id,server_code,category,title,price,description,image_url,stock) VALUES(?,?,?,?,?,?,?,?)").bind(u.id,esc(b.server_code),esc(b.category),esc(b.title),esc(b.price),b.description||"",b.image_url||null,Number(b.stock||1)).run();return out({ok:true,id:r.meta.last_row_id},201);}
if(/^\/market\/\d+$/.test(path)&&method==="PUT"){const u:any=await requireUser(request,env),id=Number(path.split("/")[2]),b:any=await request.json(),l:any=await env.DB.prepare("SELECT * FROM listings WHERE id=?").bind(id).first();if(!l||l.user_id!==u.id&&!isAdmin(u))return out({error:"forbidden"},403);await env.DB.prepare("UPDATE listings SET title=?,price=?,description=?,category=?,stock=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(esc(b.title),esc(b.price),esc(b.description),esc(b.category),Number(b.stock||1),id).run();return out({ok:true});}
if(/^\/market\/\d+$/.test(path)&&method==="DELETE"){const u:any=await requireUser(request,env),id=Number(path.split("/")[2]),l:any=await env.DB.prepare("SELECT * FROM listings WHERE id=?").bind(id).first();if(!l||l.user_id!==u.id&&!isAdmin(u))return out({error:"forbidden"},403);await env.DB.prepare("UPDATE listings SET status='DELETED' WHERE id=?").bind(id).run();return out({ok:true});}
if(path==="/admin/users"&&method==="GET"){const u:any=await requireUser(request,env);if(!isAdmin(u))return out({error:"forbidden"},403);return out((await env.DB.prepare("SELECT id,discord_id,username,display_name,region,server_code,role,disabled,created_at FROM users ORDER BY id DESC LIMIT 500").all()).results);}
if(path==="/admin/users/role"&&method==="POST"){const u:any=await requireUser(request,env);if(u.role!=="OWNER")return out({error:"owner_only"},403);const b:any=await request.json();await env.DB.prepare("UPDATE users SET role=?,updated_at=CURRENT_TIMESTAMP WHERE discord_id=?").bind(esc(b.role||"USER"),esc(b.discord_id)).run();await audit(env,u,"CHANGE_ROLE","USER",undefined,JSON.stringify(b));return out({ok:true});}
if(path==="/admin/users/status"&&method==="POST"){const u:any=await requireUser(request,env);if(!isAdmin(u))return out({error:"forbidden"},403);const b:any=await request.json();if(u.role!=="OWNER"&&b.user_id===u.id)return out({error:"forbidden"},403);await env.DB.prepare("UPDATE users SET disabled=? WHERE id=?").bind(Number(b.disabled?1:0),Number(b.user_id)).run();await audit(env,u,"CHANGE_USER_STATUS","USER",Number(b.user_id),String(b.disabled));return out({ok:true});}
if(path==="/admin/reports"&&method==="GET"){const u:any=await requireUser(request,env);if(!isAdmin(u))return out({error:"forbidden"},403);return out((await env.DB.prepare("SELECT r.*,u.display_name reporter_name FROM reports r JOIN users u ON u.id=r.reporter_id ORDER BY r.id DESC LIMIT 500").all()).results);}
if(path==="/admin/reports/status"&&method==="POST"){const u:any=await requireUser(request,env);if(!isAdmin(u))return out({error:"forbidden"},403);const b:any=await request.json();await env.DB.prepare("UPDATE reports SET status=?,review_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(esc(b.status),esc(b.review_note),Number(b.id)).run();await audit(env,u,"REVIEW_REPORT","REPORT",Number(b.id),esc(b.status));return out({ok:true});}
if(path==="/admin/notifications"&&method==="POST"){const u:any=await requireUser(request,env);if(!isAdmin(u))return out({error:"forbidden"},403);const b:any=await request.json(),rows:any=await env.DB.prepare("SELECT id FROM users WHERE disabled=0").all();for(const x of rows.results as any[])await notify(env,x.id,"ADMIN",esc(b.title),esc(b.body));await audit(env,u,"BROADCAST_NOTIFICATION");return out({ok:true,count:rows.results.length});}
if(path==="/admin/stats"&&method==="GET"){const u:any=await requireUser(request,env);if(!isAdmin(u))return out({error:"forbidden"},403);const count=async(t:string)=>Number((await env.DB.prepare(`SELECT COUNT(*) c FROM ${t}`).first() as any)?.c||0);return out({users:await count("users"),active_users:Number((await env.DB.prepare("SELECT COUNT(*) c FROM users WHERE disabled=0").first() as any)?.c||0),posts:await count("posts"),comments:await count("comments"),likes:await count("likes"),orders:await count("orders"),listings:await count("listings"),reports:await count("reports")});}
if(path==="/admin/audit"&&method==="GET"){const u:any=await requireUser(request,env);if(!isAdmin(u))return out({error:"forbidden"},403);return out((await env.DB.prepare("SELECT a.*,u.display_name actor_name FROM audit_log a JOIN users u ON u.id=a.actor_id ORDER BY a.id DESC LIMIT 500").all()).results);}
return out({error:"not_found"},404);
}catch(e:any){const code=e?.message||"server_error";return out({error:code},code==="UNAUTHORIZED"?401:500);}}};
